local opts = {
    auto_close = false,
    auto_open = false,
    auto_preview = true,
    auto_refresh = true,
    auto_jump = false,
    focus = false,
    restore = true,
    follow = true,
    indent_guides = true,
    max_items = 200,
    multiline = true,
    pinned = false,
    warn_no_results = true,
    open_no_results = false,
    win = {},
    preview = {
        type = "main",
        scratch = true,
    },
    throttle = {
        refresh = 20,
        update = 10,
        render = 10,
        follow = 100,
        preview = { ms = 100, debounce = true },
    },
    keys = {
        ["?"] = "help",
        r = "refresh",
        R = "toggle_refresh",
        q = "close",
        ["<Esc>"] = "cancel",
        ["<CR>"] = "jump",
        ["<C-l>"] = false,
        ["<C-k>"] = false,
        ["}"] = "next",
        ["]]"] = "next",
        ["{"] = "prev",
        ["[["] = "prev",
        dd = "delete",
        d = { action = "delete", mode = "v" },
        i = "inspect",
        p = "preview",
        P = "toggle_preview",
        fo = "fold_open",
        fO = "fold_open_recursive",
        foo = "fold_open_all",
        fc = "fold_close",
        fC = "fold_close_recursive",
        fcc = "fold_close_all",
        ft = "fold_toggle",
        fT = "fold_toggle_recursive",
        ftt = "fold_toggle_enable",
        fm = "fold_more",
        fr = "fold_reduce",
        fu = "fold_update",
        fU = "fold_update_all",
        fe = "fold_enable",
        fd = "fold_disable",
    },
    icons = {
        indent = {
            top = "│ ",
            middle = "├╴",
            last = "└╴",
            fold_open = "",
            fold_closed = "",
            ws = "  ",
        },
        folder_closed = "",
        folder_open = "",
        kinds = {
            Array = " ",
            Boolean = " ",
            Class = " ",
            Constant = " ",
            Constructor = " ",
            Enum = " ",
            EnumMember = " ",
            Event = " ",
            Field = " ",
            File = " ",
            Function = " ",
            Interface = " ",
            Key = " ",
            Method = " ",
            Module = " ",
            Namespace = " ",
            Null = " ",
            Number = " ",
            Object = " ",
            Operator = " ",
            Package = " ",
            Property = " ",
            String = " ",
            Struct = " ",
            TypeParameter = " ",
            Variable = " ",
        },
    },
    use_diagnostic_signs = true,
}

local keys = {
    {
        "<leader>td",
        "<cmd>Trouble diagnostics toggle<cr>",
        mode = "n",
        desc = "Diagnostics (Trouble)",
    },
    {
        "<leader>tD",
        "<cmd>Trouble diagnostics toggle filter.buf=0<cr>",
        mode = "n",
        desc = "Buffer Diagnostics (Trouble)",
    },
    {
        "<leader>ts",
        "<cmd>Trouble symbols toggle focus=false win.position=right win.size=40<cr>",
        mode = "n",
        desc = "Symbols (Trouble)",
    },
    {
        "<leader>tl",
        "<cmd>Trouble lsp toggle focus=false win.position=right<cr>",
        mode = "n",
        desc = "LSP Definitions / references (Trouble)",
    },
    {
        "<leader>tL",
        "<cmd>Trouble loclist toggle<cr>",
        mode = "n",
        desc = "Location List (Trouble)",
    },
    {
        "<leader>tQ",
        "<cmd>Trouble qflist toggle<cr>",
        mode = "n",
        desc = "Quickfix List (Trouble)",
    },
}

return {
    "folke/trouble.nvim",
    dependencies = { "nvim-tree/nvim-web-devicons" },

    cmd = { "Trouble" },

    opts = opts,
    keys = keys,
}
